name: DrakonnasEssentials
main: com.comze_instancelabs.drakonnasessentials.Main
version: 1.0
author: InstanceLabs
commands:
   info:
      description: Shows info and plugin version.
      usage: /<command>
      permission: <plugin name>.info
      permission-message: You don't have permission!
      aliases: [version]
commands:
   osinfo:
      description: Shows info about the server operating system.
      usage: /<command>
      permission: <plugin name>.osinfo
      permission-message: You don't have permission!
      aliases: [os]